### ISSUE TITLE
Geogebra Classic 6

### ISSUE THREAD

**Issue by Duvio** [geogebra/math-apps-examples#1]
Geogebra Classic 6 is not available in the other repository https://github.com/geogebra/geogebra, the most up to date version is 5.2. Is it supposed to be like that? And if not, roughly when will the repo have caught up to the latest version?

**Comment by kovzol** [comment]
It's there, version 6 coexists with version 5. Just compile the web version, it is identical to version 6. The desktop variant of Classic 6 is not present in the source tree and it is not intended to be provided publicly.
